services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cara
    ports:
      - '5432:5432'

  solver:
    build:
      context: ./solver
      dockerfile: Dockerfile.solver
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: cara
    volumes:
      - ./solver/app:/solver/app
    depends_on:
      - db
    restart: always
    ports:
      - '8080:8080'
